### ISSUE TITLE
Update Fedora COPR repo to Version 0.5.2

### ISSUE THREAD

**Issue by lemonzest79** [yggdrasil-network/yggdrasil-package-rpm#15]
As title really, thanks

**Comment by neilalexander** [comment]
Build taking place: https://copr.fedorainfracloud.org/coprs/neilalexander/yggdrasil-go/build/6606604/

**Comment by lemonzest79** [comment]
Thanks :)

**Comment by neilalexander** [comment]
Looks like it's done, thanks for the reminder!
